# Generated by Django 5.2 on 2025-05-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_project_user_projectstatus_color_projectstatus_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
