# Generated by Django 5.2 on 2025-05-22 22:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_alter_material_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['-date', '-start_time']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='materialusage',
            options={'ordering': ['-used_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date', 'name']},
        ),
        migrations.AddField(
            model_name='dailylog',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='work_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='used_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='materialusage',
            name='used_quantity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='MaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('buy_at', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='diary.material')),
            ],
            options={
                'ordering': ['-buy_at'],
            },
        ),
        migrations.DeleteModel(
            name='MaterialAdd',
        ),
    ]
